#FROM java:8
#LABEL maintainer=“kings86170@gmail.com”
#VOLUME /tmp
#EXPOSE 8080
#ADD target/aot_preview-0.0.1-SNAPSHOT.jar aot_preview-0.0.1-SNAPSHOT.jar
#ENTRYPOINT ["java","-jar","aot_preview-0.0.1-SNAPSHOT.jar"]
